### ISSUE TITLE
404 pages on the documentation

### ISSUE THREAD

**Issue by Gustry** [GothenburgBitFactory/tw.org#105]
#### To report a bug...

I think there is a problem with the documentation.

https://taskwarrior.org/docs/commands/

There is a lot of commands disabled, maybe because the page doesn't exist ?

At the bottom of https://taskwarrior.org/docs/commands/modify.html
there is a link to "edit" which leads to 404 as well ?

Sorry if I have missed something.

I'm trying to learn the documentation how to edit a task. (I forgot yesterday to stop the timer).

**Comment by tbabej** [comment]
Hi @Gustry,

this command is indeed not documented on the website itself (all commands documented on the website have links [on this summary page](https://taskwarrior.org/docs/commands/), which you link to). The best reference for commands is the manpage, available through `man task`, or in this repo in its [source code form](https://github.com/GothenburgBitFactory/taskwarrior/blob/8ffb85b3278ef15d6d77c854064f5e0afa6b40c5/doc/man/task.1.in#L369).

**Comment by Gustry** [comment]
Ok, thanks. I found some in the timew documentation indeed.
SHould I keep the ticket open for the 404 on https://taskwarrior.org/docs/commands/modify.html at the bottom ? (the link to `Edit`)

**Comment by tbabej** [comment]
Indeed, it should be open. Even better would be contributing a fix :slightly_smiling_face: the source code for the website is in this repo.

**Comment by lauft** [comment]
I added a PR where I fixed a bunch of links, as well as deactivated those where the target, i.e. the command documentation, does not exist.

Shall we add an issue for each missing command documentation?
