### ISSUE TITLE
Add my new gtd-review project

### ISSUE THREAD

**Issue by jonathanabennett** [GothenburgBitFactory/tw.org#139]
gtd-review is a project-centric review tool meant to supplement `tasksh review`. It is under active development and I'm hoping within the next 2-3 weeks to complete most of what's on the roadmap in the README.

Can you please add it to the tools page on the site?

**Comment by lauft** [comment]
The content of the tools page is generated automatically by a daily Job which queries the Github API for repositories containing the keyword taskwarrior, or taskserver in their name, description, or as topic.

I guess the safest way is to add the topic.

**Comment by tbabej** [comment]
@lauft I believe Jonathan added a topic the very day you suggested it, but it still seems like it was not picked up by the Github workflow job? I can't see the repo

https://github.com/jonathanabennett/gtd-review/

among the listed tools yet.

**Comment by lauft** [comment]
@tbabej You are right. I ran it locally today (2021-06-30) but it was not delivered by the Github API...

**Comment by lauft** [comment]
@tbabej @jonathanabennett I have added the tool manually. It is now listed on the tools page.
