### ISSUE TITLE
taskwarrior.org/tools update script is broken

### ISSUE THREAD

**Issue by recollir** [GothenburgBitFactory/tw.org#2]
@pbeckingham: "Something changed with the GitHub API and/or Github python code so that we can no longer automatically scan github and regenerate the data that drives the tools page."

Moved here from GothenburgBitFactory/infrastructure#7

**Comment by tbm** [comment]
Any news on this?  As a newcomer, it's a bit disconcerting that every tool entry says "Last update: 2017".

**Comment by lauft** [comment]
The update script seems to have been replaced by an "internal" version in 2019 (see #69)
The tools page itself has been updated. The entries should be now (2021-01-07) more recent.
