### ISSUE TITLE
[WWW-16] Fix holiday type on Christmas en-GB 2016

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/tw.org#22]
_Richard Brown on 2016-09-29T08:55:43Z says:_ 

 When Christmas day is in a Sunday it's not the national holiday anymore?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-29T08:55:43Z
Modified: 2016-09-29T12:42:03Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-09-29T12:42:03Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[WWW-16_0001-Fix-holiday-type-on-en-GB-Christmas-2016.patch.txt](https://github.com/GothenburgBitFactory/tw.org/files/1755293/WWW-16_0001-Fix-holiday-type-on-en-GB-Christmas-2016.patch.txt)
