### ISSUE TITLE
[WWW-17] I think some files weren't added after the last build

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/tw.org#23]
_Richard Brown on 2016-09-29T08:58:44Z says:_ 

 I think you forgot to git add the new 2017/18 files for en-US en-GB, I've attached the output after applying the change I did to en-GB, but I assume it's probably easier for you to just add them yourself

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-29T08:58:44Z
Modified: 2016-09-29T12:42:24Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-09-29T12:42:20Z says:_ 

 Absolutely right.  Files were missed.  Thank you.

**Comment by pbeckingham** [comment]
[WWW-17_0002-Add-new-2017-2018-generated-files.patch.txt](https://github.com/GothenburgBitFactory/tw.org/files/1755294/WWW-17_0002-Add-new-2017-2018-generated-files.patch.txt)
