### ISSUE TITLE
Add 2.6.1 announcement to news

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/tw.org#267]
The latest post on https://taskwarrior.org/ is for 2.5.3!

Is there a set of steps for this somewhere, or a script?  I'm happy to do it but guessing at how is unlikely to be productive :)

**Comment by tbabej** [comment]
No script yet, but it is something we could automate after the markdown setup is in! :slightly_smiling_face:

**Comment by djmitche** [comment]
Sounds great :)

**Comment by tbabej** [comment]
I added a 2.6.0 announcement to the website last night in ebe22a8. Not sure if patch releases should be individually announced, Ithough  guess that could be useful for users that build from source and don't follow our github page :thinking:

**Comment by djmitche** [comment]
Yay!

**Comment by djmitche** [comment]
At least at the moment, when announcements are a bit tricky, skipping patch releases sounds reasonable.
