### ISSUE TITLE
Synergies

### ISSUE THREAD

**Issue by ddeimeke** [GothenburgBitFactory/tw.org#3]
The unexpected synergies and benefits of having a physical meet up, with our FOSDEM trips in mind.  Getting together, meeting, sharing time, volunteering on the spot.  The productivity is amazing, provided the actions are not the typical bug fix/test type.  Learning that personA really wansts to do this, and personB doesn’t, which is much clearer in a meeting context. Watching personA work motivates personB.

**Comment by lauft** [comment]
Closing this because of old age.
