### ISSUE TITLE
FAQ typo, no projects is `project == ''`, not `project != ''`

### ISSUE THREAD

**Issue by bradyt** [GothenburgBitFactory/tw.org#326]
At https://taskwarrior.org/support/faq.html#q3,

> Q: How do I list tasks that have no project?
> 
> There are a few ways:
> 
>     $ task project.none: list
>     $ task project: list
>     $ task project != '' list
>     $ task -PROJECT list
> 
> The last example makes use of a virtual tag designed for this use case, and is the preferred mechanism.
> 
> To list tasks that do have a project assigned, you can use these alternates:
> 
>     $ task project.any: list
>     $ task project.not: list
>     $ task project == '' list
>     $ task +PROJECT list

It looks like the `!=` and `==` should be swapped.

**Comment by NaincyKumariKnoldus** [comment]
Hey @bradyt I have fixed this. I have raised a PR for this. Please review this.
Thanks!

**Comment by bradyt** [comment]
Yes, that looks right to me. Thank you!
