### ISSUE TITLE
What regex grammar is used?

### ISSUE THREAD

**Issue by jean** [GothenburgBitFactory/tw.org#35]
Clarify the [regex docs](https://github.com/GothenburgBitFactory/tw.org/blob/914039b6d5e5b04e6206121e0bb4438db5fcd503/html/docs/terminology.html#L705).
The C++ code uses the [standard library](https://docs.microsoft.com/en-us/cpp/standard-library/regular-expressions-cpp) implementation which supports 6 different grammars and several flags. It looks like it may be defaulting the `ECMAScript` grammar.
However the tests in Python use the Python `re` module. 
Where exactly should we look for the supported grammar?

**Comment by pbeckingham** [comment]
No, the code does not use std::regex, see ‘man regex’.

Paul

**Comment by jean** [comment]
@pbeckingham OK, so what you're saying is that taskwarrior uses POSIX regular expressions. In that case this is what the docs should state. 
It's still not clear though: what `cflags` and `eflags` are in use --- i.e. is it using _Extended_ or _Basic_ regular expressions, how are newlines matched? 
An example like `$ task /fo{2}/ long` [ref](https://taskwarrior.org/docs/searching.html#regexes) implies that it's _Extended_ POSIX regexps. 

It looks like [this chapter](https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions) would be a good reference.
