### ISSUE TITLE
Things 3 -> Taskwarrior Script

### ISSUE THREAD

**Issue by evantravers** [GothenburgBitFactory/tw.org#354]
I gave https://github.com/mpapierski/things2taskwarrior a whirl, but it's out of date with current versions of Things 3. I had already written a Things to Orgmode conversion, so I thought I'd learn more about Taskwarrior by writing a JSON export too.

Edit: Forgot my link! https://github.com/evantravers/ThingsToTaskwarrior

**Comment by lauft** [comment]
Thanks @evantravers! 
You have already added the topic `taskwarrior` to the repository, so your tool should appear in [the listing](https://taskwarrior.org/tools) after the next run of our GitHub crawler.

**Comment by lauft** [comment]
It is now listed. There was an issue with the update job, therefore it took a bit longer.
