### ISSUE TITLE
Verbosity Tokens "unwait", "new-uuid" and"context" are not listed 

### ISSUE THREAD

**Issue by StefanBRas** [GothenburgBitFactory/tw.org#36]
Hello.

In the ["Verbosity"](https://taskwarrior.org/docs/verbosity.html) sections of the docs the tokens:

- unwait
- new-uuid
- context

are not listed.

"unwait" and "new-uuid" can be found with "task info" and looking at the default value of "verbose", but "context" was a guess since the ["Context"](https://taskwarrior.org/docs/context.html) section of the docs mentions that "There will be a footnote after every report that reminds you of the current context." This does not seem to be default behavior in taskwarrior 2.5.1, so perhaps the section should be changed or the default value.

**Comment by jdorel** [comment]
Fixed (has yet to be merged) through :
  - #99 
  - #100 
  - #101

**Comment by jdorel** [comment]
@tbabej  I believe this issue can be closed.

**Comment by StefanBRas** [comment]
I believe so too, thanks for fixing it!
