### ISSUE TITLE
TANSTAAFL

### ISSUE THREAD

**Issue by ddeimeke** [GothenburgBitFactory/tw.org#4]
What we learned about free services. RackSpace charges Fredde every year, forgets our open source status, and eventually makes us want to migrate off just to make it stop.  Atlassian free license, self-hosting, and the misery of upgrading and keeping products linked together.  Github outages (mostly DNS attacks, if I recall) that keep us reluctant to switch.  Fear of using many features of any provider because of lock-in.  Custom migration paths (Tomas script for Jira -> GH issues).  All kept anonymous of course, but perhaps offering wisdom for people about to accept free services.  Now I think of it, this could be more of a talk than a blog article.

**Comment by recollir** [comment]
To be honest, we asked for "sponsorship". But there are companies that handle that process better than others. That said, even when being a paid customer we would be suffering from DDoS attacks, not matter what service we are using or whoever is hosting our VPS or real HW servers.

Regarding the lock in. That even applies to FOSS - our move away from redmine is a good example (at that time we just decided to not migrate any issues at all - IIRC). And the self hosting of redmine came also with pain. 

The only piece not having caused us much trouble is git in itself. In the end it is just a matter of which level of "Undifferentiated heavy lifting" one wants to avoid.

**Comment by lauft** [comment]
Closing this because of old age.
