### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by jonathanfallon** [GothenburgBitFactory/tw.org#40]
Hi !

The cert is down on the website today.

![taskwarrior-cert](https://user-images.githubusercontent.com/1656255/37396779-27c7be6c-277a-11e8-8b9d-0fbda800e17a.png)

**Comment by taskwarrior** [comment]
Give it a couple of minutes until DNS propagates and a new Let's Encrypt cert can be issued after moving the site to Netlify hosting.
