### ISSUE TITLE
dead link in done.html

### ISSUE THREAD

**Issue by phanos** [GothenburgBitFactory/tw.org#44]
Dead link in done.html. docs/commands/delete.html does not exist

https://github.com/GothenburgBitFactory/tw.org/blob/6ce015b8806b4ed131f189f302e935a91c77cc1f/html/docs/commands/done.html#L144

**Comment by ddeimeke** [comment]
Resolved via https://github.com/GothenburgBitFactory/tw.org/commit/3d62ff81088573b7d63407fc0e36865b8cbaa9bc
