### ISSUE TITLE
timew-billable: language updated

### ISSUE THREAD

**Issue by trev-dev** [GothenburgBitFactory/tw.org#466]
I recently refactored timew-billable to nim!  The listing currently displays Python.  I am not sure if this metadata updates, so here's an issue.

https://github.com/trev-dev/timew-billable

**Comment by lauft** [comment]
@trev-dev Sometimes the crawler takes a bit longer to update. Since 14.11.2022 (ec37fa54) it is listed with `Nim` as its language
