### ISSUE TITLE
Add tw-pm to tools page

### ISSUE THREAD

**Issue by jahagirdar** [GothenburgBitFactory/tw.org#483]
https://github.com/jahagirdar/tw-pm

Yet another web based Taskwarrior frontend implementing the GTD methodology. This one has all the flashiness of a Single page applications and is build with project management and status updates during meetings in mind.

**Comment by lauft** [comment]
@jahagirdar The tools page is aggregated automatically by querying the GitHub API. Your project is already listed because it mentions 'taskwarrior' in the description. However, this is not guaranteed to be stable. The safest way is to add the topic `taskwarrior` to your project.
