### ISSUE TITLE
Taskserver, nothing else

### ISSUE THREAD

**Issue by ddeimeke** [GothenburgBitFactory/tw.org#6]
Why Taskserver is the only acceptable method for syncing tasks, and why DropBox (etc) are not.

**Comment by sampablokuper** [comment]
One reason not to use DropBox is that it can (or could, as of c.2015) lose data. See: [*A Deep Specification for Dropbox*](https://www.youtube.com/watch?v=Y2jQe8DFzUM) - Benjamin Pierce (2015).

**Comment by lauft** [comment]
Closing this because of old age.
