### ISSUE TITLE
Build instructions for taskwarrior refer to non-existing master branch

### ISSUE THREAD

**Issue by runelk** [GothenburgBitFactory/tw.org#612]
Not a big deal, but I just noticed that the [build instructions](https://taskwarrior.org/docs/build/) on [taskwarrior.org](https://taskwarrior.org) says to checkout master for building the stable version, which doesn't seem to exist in the [taskwarrior repo](https://github.com/GothenburgBitFactory/taskwarrior/branches/all). I'm currently going through the setup and build process, so if you want I could make a quick PR for the [build.md](https://github.com/GothenburgBitFactory/tw.org/blob/master/content/docs/build.md) doc when I'm done building taskwarrior locally.

**Comment by djmitche** [comment]
Hm, those should point to the in-repo instructions now -- https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/README.md. A PR would be great!

**Comment by runelk** [comment]
> Hm, those should point to the in-repo instructions now

Is there anything specific you use to refer to docs in that repo in this repo, or should I just update the .md file in this repo manually?

**Comment by djmitche** [comment]
Just a regular markdown link is fine.

**Comment by runelk** [comment]
@djmitche Just checking if you need anything on the PR? Forgot to mention that I changed the instructions for dev as well as they seem to have moved from numbered branches to version tags, using the develop branch for the latest changes.

**Comment by djmitche** [comment]
Thank you!
