### ISSUE TITLE
Update `inthe.am` Description in Taskwarrior's Add-On List

### ISSUE THREAD

**Issue by kenthorvath** [GothenburgBitFactory/tw.org#617]
The current description for `inthe.am` in the Taskwarrior add-on list is: 
> Access your Taskwarrior tasks from any browser anywhere.

To provide a more comprehensive overview, especially for users looking for a `freecinc` replacement, I suggest updating the description as follows:

```markdown
**Inthe.AM** provides a free `taskd` service. More details [here](https://inthe.am/).

**Features:**

- **Built-In Taskserver**: Sync with your local Taskwarrior client.
- **E-mail**: Add tasks via a whitelist-controlled email address.
- **RSS Feeds**: View tasks in any RSS reader.
- **Trello**: Use Taskwarrior tasks with Trello boards.
- **iCal Feed**: See tasks in Google Calendar.
- **SMS**: Add tasks via SMS using Twilio.
- **Mobile Web UI**: Optimized for mobile and desktop. Web-app mode available for iPhone users.
- **Open Source**: Built on open-source. Feature requests and suggestions can be made [here](https://github.com/coddingtonbear/inthe.am/issues?page=1&state=open).
- **RESTful API**: Manage tasks with the provided API.

**Comment by djmitche** [comment]
Sounds great -- do you want to make a PR?

**Comment by lauft** [comment]
@kenthorvath The entries on this list are taken from the respective projects by our crawling script, the text
> Access your Taskwarrior tasks from any browser anywhere.

is the current project description. In order to change this you would have to talk to the maintainer of [inthe.am](https://github.com/coddingtonbear/inthe.am).

**Comment by kenthorvath** [comment]
Thanks @lauft - I forwarded this to the maintainer of inthe.am, and I think we can close this out now.
