### ISSUE TITLE
Task board is no longer active and the repository is archived

### ISSUE THREAD

**Issue by Marco-Kaulea** [GothenburgBitFactory/tw.org#649]
I don't know what the requirements are to be listed, but the author does not recommend the project anymore.
https://github.com/desbma/task-board

**Comment by lauft** [comment]
The requirement is to have `taskwarrior` mentioned in title or description, or as topic. If the project is archived, it is listed as 'dormant', which is the case here.

Maybe we should switch the checkbox on the [tools page](https://taskwarrior.org/tools/) to 'include dormant projects', such that archived projects are not listed by default. 🤔
