### ISSUE TITLE
Contradictory information on multi line descriptions

### ISSUE THREAD

**Issue by devurandom** [GothenburgBitFactory/tw.org#66]
* https://taskwarrior.org/docs/examples.html describes how to "create a task with a multi-line description"
* https://taskwarrior.org/docs/commands/add.html says that "Task descriptions may only contain one line of text. Taskwarrior will wrap that text when it is displayed, but there is no means of entering multi-line tasks."

These two are obviously in conflict, and it seems that the first one is correct.

**Comment by ageonic** [comment]
Hello, it looks like this is still an issue. I have added a potential fix in [`4d75172`](https://github.com/ageonic/tw.org/commit/4d751726d1cafae0126508b4253d74e14ffab560). Would a pull request be welcome?

**Comment by lauft** [comment]
@ageonic updates of the documentation are always welcome. 🤗
