### ISSUE TITLE
sod with wrong description

### ISSUE THREAD

**Issue by Spacewalker2** [GothenburgBitFactory/tw.org#77]
Hello, there is a little error [here](https://taskwarrior.org/docs/named_dates.html). In the table and in the image sod is describted for today but I believe it is actually tomorrow.

**Comment by jdorel** [comment]
Hi,
`sod` is defined in [there](https://github.com/GothenburgBitFactory/libshared/blob/df7267c75c0d77f5356c7c9b9028d9100590c6e6/src/Datetime.cpp#L1649).

As you can seem `sod` is the beginning of current day :
```
struct tm* t = localtime (&now);
t->tm_hour = t->tm_min = t->tm_sec = 0;
t->tm_isdst = -1;
```
You can also test locally with `task add test due:sod`, then `task <id> info`. The due date will be today.

But there is a mismatch in the [`dates` page](https://taskwarrior.org/docs/dates.html) of the documentation. Maybe the `synonyms` section should just point to the `named_dates` page ?
