### ISSUE TITLE
in.the.am shutdown

### ISSUE THREAD

**Issue by bidaian** [GothenburgBitFactory/tw.org#770]
in.the.am is still listed among the tools, but it [no longer works](https://github.com/coddingtonbear/inthe.am/discussions/427) since 2024.01.03:

The [code is available](https://github.com/coddingtonbear/inthe.am) but [it's not meant to be used to host a clone](https://intheam.readthedocs.io/en/latest/): 

> Setting this up locally as a clone of Inthe.AM is, unfortunately, not supported.

Could you please remove it from the tools or make a note about its current status?

**Comment by djmitche** [comment]
It looks like 02eb1206 was intended to fix this, but it was overwritten in 2aefb13a6 by the bot.

**Comment by djmitche** [comment]
Ah, if the repo is archived then the automation will reflect that locally. @coddingtonbear WDYT about marking https://github.com/coddingtonbear/inthe.am as archived?

**Comment by djmitche** [comment]
Well, I think that's the fix -- nothing to be done here.
