### ISSUE TITLE
tools page: not clear how to submit feedback

### ISSUE THREAD

**Issue by tbm** [GothenburgBitFactory/tw.org#81]
https://taskwarrior.org/tools/ says:

>  Do you have a taskwarrior extension you'd like to see listed here? Do you have any corrections to suggest? Please tell us about it. 

I think "Please tell us about it" should be a link to a feedback form, email address or this bug tracker.  Right now it's not clear how to submit feedback.

**Comment by lauft** [comment]
I have updated the page text and added a link to this issue tracker here. Thanks for your feedback! 👍🏻
