### ISSUE TITLE
Show in.the.am as archived

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/tw.org#824]
Quoted from https://github.com/GothenburgBitFactory/taskwarrior/issues/3469:

> As stated in https://github.com/coddingtonbear/inthe.am/discussions/427 Inthe.am service is no more.
>
> This (sad, but true) fact needs to be labelled as such in the [tools ](https://taskwarrior.org/tools/)page, to avoid false hopes.

Add https://github.com/coddingtonbear/inthe.am to `blacklist.json` and add it manually as archived

**Comment by djmitche** [comment]
BTW, you can "transfer" issues (in the bottom of the menu on the right side)
