### ISSUE TITLE
"[taskwarrior] uses human-readable text files for storage" in docs/start might be outdated

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#835]
sqlite3 databases are used since version 3 (I think).

Maybe [this text](https://github.com/GothenburgBitFactory/tw.org/blob/master/content/docs/start.md?plain=1#L36) could be slightly rephrased for clarity. I understand that SQL databases are quite readable too, but this might suggest that it uses plain text files.

**Comment by djmitche** [comment]
You're correct. We'd also like to avoid encouraging modifying the SQL database directly. While it's possible to do so, there are some intricate internal consistency requirements that are hard to maintain via SQL queries.

Do you want to make a PR?
