### ISSUE TITLE
docs/introduction says that task data directory is empty initially, but it contains an empty sqlite database

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#836]
[source](https://github.com/GothenburgBitFactory/tw.org/blob/2bda44fc96d9de3bf9a1d7fee7be0ef35a1fdf80/content/docs/introduction.md?plain=1#L70)

**Comment by djmitche** [comment]
Thanks! Do you want to make a new PR?
