### ISSUE TITLE
Clarify status of "Attribute Modifiers" deprecation

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#854]
The `docs/deprecated` page says the following:

> ### Attribute Modifiers [deprecated since 2.4.0]
> 
> Attribute modifiers such as `project.startswith:Ab` are all deprecated starting with version 2.4.0.
> In the example above, the replacement is an algebraic expression, `project ~ ^ab`, which uses the `~` regex match operator, and `^Ab` which is a regular expression.

A couple of questions here:
- Are all "Attribute Modifiers" deprecated? Or only those related to string matching such as `word`, `has` and so on? Or are only `startswith` and `endswith` are deprecated?
- Could these deprecations be added to the man pages? Nothing in the "Attribute Modifiers" section of `task(1)` mentions deprecation.
- Could the `~` regex match operator be documented in the man pages? I find no mention of it

**Comment by djmitche** [comment]
I wonder if this, and the deprecation of the alternative spellings of true and false mentioned in #855, are overly-aggressive deprecations? I don't imagine we'd ever actually remove support for these, as that would be a pretty disruptive change for users with little benefit for developers.

@tbabej was that before your time?

**Comment by tbabej** [comment]
I remember this, personally I didn't agree with deprecating the attribute modifiers, and I think we should cancel the deprecation.

I believe the original motivation was to simplify the code / feature set, but in my experience, the attribute modifiers are much more natural way of expressing relationships, as they do not require shell escapes or remembering the syntax. I personally use them all the time.

Furthermore, both tasklib and taskw libraries (and likely others) rely on their existence.

**Comment by sebastiancarlos** [comment]
Feel free to close issue if you decide to revert the deprecation

**Comment by djmitche** [comment]
Sounds good - filed https://github.com/GothenburgBitFactory/tw.org/issues/867 to track that.
