### ISSUE TITLE
Update boolean configuration with values other than 0 or 1 from the docs

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#855]
There are many examples in the docs of boolean values other than 0 or 1, such as "on".

According to [this page](https://taskwarrior.org/docs/deprecated/), they are deprecated. Should they all be updated?

**Comment by djmitche** [comment]
Yes, that seems like a good idea!

**Comment by sebastiancarlos** [comment]
Feel free to close issue if you decide to revert the deprecation, as per https://github.com/GothenburgBitFactory/tw.org/issues/854#issuecomment-2185595971

**Comment by djmitche** [comment]
Closing in favor of https://github.com/GothenburgBitFactory/tw.org/issues/867.
