### ISSUE TITLE
Clarify that priority values order does not change urgency coefficient

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#857]
Some examples in the documentation might suggest that changing UDA values also changes their urgency, but that's not the case. Maybe a clarification could be added there.

From docs/priority:

> ## Custom Configuration
> 
> If you believe that a priority level of `L` should be the lowest value, lower even than no value, you can do this:
> 
> ```
> $ task config uda.priority.values H,M,,L
> ```
> 
> Those two commas indicate that the blank value lies between `M` and `L`.

Also from docs/examples:

> ## Priority
> 
> Priority is now a [User Defined Attribute](../udas/) since version 2.4.3, and as such can be configured.
> 
> Make priority `L` sort lower than no priority.
> 
> ```
> $ task config uda.priority.values H,M,,L
> ```

**Comment by djmitche** [comment]
I'd suggest just making a PR with your desired change! I'm not sure from what you've written above what you mean -- the two quoted bits of docs do not relate to urgency.
