### ISSUE TITLE
Clarify meaning of "ID"s and "Garbage Collection" now that there are no `*.data` files

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/tw.org#877]
From the docs:

> ## ID Numbers
> 
> Taskwarrior assigns ID numbers to tasks. The ID number is actually a simple line count of the entries in the `pending.data` file. When a task is completed or deleted, it is moved to the `completed.data` file, and loses the ID.
> ...
> One downside is that ID numbers change occasionally, although in a predictable way.

> ## Garbage Collection
> 
> When a task is marked as deleted, it gets a new status, and an `end` attribute, among other things.
> The task is written back into the `pending.data` file, but it doesn't belong there - it belongs in the `completed.data` file.
> There is an operation called Garbage Collection (gc) that is automatically run by taskwarrior to move tasks into the correct files.
> When moving tasks between the files, ID numbers are affected, because they are simply line numbers in the `pending.data` file.

By looking at the `taskchampion` codebase, it seems the term "working set" might replace `pending.data`, and "rebuild" might replace "garbage collection". Noting also that a new "garbage collection" term is now used instead to refer to the automated removal of tasks with a `modified` property more than 180 days in the past.

If I get it correctly, the "working set" keeps track of the current tasks (mostly pending and recurrent tasks) and assigns incremental 1-indexed IDs to them. Periodically, the "working set" is rebuilt to remove completed or deleted tasks, and to remove gaps in the numbering by shifting the IDs downwards.

**Comment by djmitche** [comment]
You're correct about the working set and rebuilding. This was implemented in such a way that the behavior should be the same ("change occasionally, although in a predictable way").

The process of expiring older tasks is called "expiring", chosen specifically to avoid the word "deleting". I see from grepping the TC repository that I was a little loose in some comments:
```
⸩ git grep 'garbage'
docs/src/taskdb.md:Actual removal of tasks from the task database takes place as part of _expiration_, triggered by the user as part of a garbage-collection process.
taskchampion/src/replica.rs:/// during the garbage-collection process.
taskchampion/src/storage/mod.rs:    /// Clear all tasks from the working set in preparation for a garbage-collection operation.
```
and I'll make a quick PR to fix those up.
