### ISSUE TITLE
Documentation on 'tools' page is 3+ years out of date

### ISSUE THREAD

**Issue by Robinlovelace** [GothenburgBitFactory/tw.org#91]
This report is not so much a feature but an issue with the documentation of tools: it's way (3+ years) out of date, with the latest updates to any project being 3 years ago here https://taskwarrior.org/tools/ which is not true and rather off-putting to newcomers to the project (like me).

On that not though I'm really happy with what I see so far, thanks for a great project! If you want support updating that page let me know, shouldn't be a big job I imagine.

**Comment by lauft** [comment]
@Robinlovelace The tools page could really require some update. The best thing would be to transform it into an Github action which runs regularly, so the burden of manual update is lifted. Another idea would be to split off all Timewarrior related tools and present them on timewarrior.net instead.

**Comment by Robinlovelace** [comment]
Sounds like it needs to be split out into a definite 'to-do' (or rather taskwarrior ; ) task. Happy to help but suspect I lack the skills/experience to make your suggestion, which sounds eminently sensible, happen.

**Comment by lauft** [comment]
@Robinlovelace Apart from the Github-Action stuff, there are some other ideas one could work on:
* Integration of Gitlab, Bitbucket,... (tools on those have to be added manually)
* Stabilize sorting in the json dump. Currently, successive runs of `update.py` yield different sortings in `tools-data.js`
* Detect & exclude empty repositorys. Maybe print a warning, if a repository has a too low file count?
* Detect correct project language (currently the language with the most lines wins, maybe switch to Github's GraphQL API?)
* ...
See also #69

**Comment by Robinlovelace** [comment]
Sounds good but still seems far from a concrete, actionable suggestion. Just a one-off update could be a good start. I could try generating some html with searchable interactivity e.g. using the JavaScript library DataTables: https://rstudio.github.io/DT/ if that would help?

**Comment by lauft** [comment]
> Just a one-off update could be a good start

I have re-run the update script, the tools listing should be more up-to-date now.

> I could try generating some html with searchable interactivity e.g. using the JavaScript library DataTables: https://rstudio.github.io/DT/ if that would help?

Maybe, if we leave out `R` 😉...
The current implementation seems to be done with [knockoff](https://knockoutjs.com/), but the search is a bit broken. I have neither experience with this or your framework, so I am quite indifferent concerning a working implementation as long as it is lightweight. Another point to consider would be that we are planning to move the Taskwarrior (and Timewarrior) webpage to [Hugo](https://gohugo.io/), so it should be possible to integrate the page into such a setup as well.

As far as I see it, the task has two parts:
* the script which crawls/querys Github (and maybe later other sources) and filters/stores the tools found (currently this is `html/tools/tools-data.js`)
* the webpage which presents the data
Both parts have their issues which need to be fixed. For the crawler I have already stated some above. For the webpage it is mainly the broken search, but the presentation of the tools itself could be optimized. A flexible sorting (by rating/(main) language/...) and/or filtering is also something helpful...

**Comment by Robinlovelace** [comment]
Great work @lauft, the specific issue is now fixed :tada:

Regarding the follow-on actions they are probably best handled in separate, specific issues. It sounds like you've got a clear idea of what to do and how so, unless you need extra support, will leave it to others with more experience of the brilliant open source project.

Great to see the page up-to-date again!

![image](https://user-images.githubusercontent.com/1825120/104024147-90339a80-51ba-11eb-8c4a-4adea343a197.png)

**Comment by lauft** [comment]
A lucky day, it seems I also fixed the search. It now also respects the tool's name... 😂
