### ISSUE TITLE
There is a deadlink on the documentation website

### ISSUE THREAD

**Issue by Robinlovelace** [GothenburgBitFactory/tw.org#92]
To reproduce the issue:

- Navigate to https://taskwarrior.org/docs/
- Click on the link that says "Taskserver Setup Guide": https://gitpitch.com/GothenburgBitFactory/taskserver-setup#/
- You should see a message that says: GitPitch.com is shutting down.

**Comment by lauft** [comment]
The Guide is still available, but only until March 1, 2021. So we need a replacement. Any suggestions?

**Comment by lauft** [comment]
The source code for the slides can be found here: https://github.com/GothenburgBitFactory/taskserver-setup. 
Maybe convert it into a reveal.js slideshow?

**Comment by tbabej** [comment]
Closing, as this was addressed in https://github.com/GothenburgBitFactory/tw.org/commit/98ffa83393c951eb879add3b91a4b7c43bb9f6e3 by @lauft 23 days ago.
