### ISSUE TITLE
Update taskwarrior release numbers to latest

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/tw.org#963]
This means currently for stable it should be `3.1.0` and idk which one for the develop. :)

**Comment by djmitche** [comment]
Oh, that's in the [release checklist](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/releasing.md), I think. I wonder if I missed it.

3.2.0 should be the next.

**Comment by djmitche** [comment]
ping -- how's this going?

**Comment by felixschurk** [comment]
I was a bit to busy the last few weeks, but now it should be done.

**Comment by djmitche** [comment]
Thanks!!
